// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfvh-R-4g33d8f572I1E6M28sgxbI9F9I',
    appId: '1:101736953975:web:ab9efec6d63092d71a6e72',
    messagingSenderId: '101736953975',
    projectId: 'ntx-app',
    authDomain: 'ntx-app.firebaseapp.com',
    storageBucket: 'ntx-app.appspot.com',
    measurementId: 'G-YWRFKMRPK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-XNZdaJfHPKSHTnC5Fz_Sxk_2WG0XaQ4',
    appId: '1:101736953975:android:18b15708e047fa261a6e72',
    messagingSenderId: '101736953975',
    projectId: 'ntx-app',
    storageBucket: 'ntx-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFWPuOPPtUHw7zWlw9MieARG8tl-Vi_G0',
    appId: '1:101736953975:ios:cbd6a3a3e24fa7e81a6e72',
    messagingSenderId: '101736953975',
    projectId: 'ntx-app',
    storageBucket: 'ntx-app.appspot.com',
    androidClientId:
        '101736953975-aj0s6ivvqnnsdu31rtmpao7nq326ghes.apps.googleusercontent.com',
    iosClientId:
        '101736953975-59uh7c23lbr8ni4ihr19uvijrtlu0bms.apps.googleusercontent.com',
    iosBundleId: 'com.example.base_code',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFWPuOPPtUHw7zWlw9MieARG8tl-Vi_G0',
    appId: '1:101736953975:ios:cbd6a3a3e24fa7e81a6e72',
    messagingSenderId: '101736953975',
    projectId: 'ntx-app',
    storageBucket: 'ntx-app.appspot.com',
    androidClientId:
        '101736953975-aj0s6ivvqnnsdu31rtmpao7nq326ghes.apps.googleusercontent.com',
    iosClientId:
        '101736953975-59uh7c23lbr8ni4ihr19uvijrtlu0bms.apps.googleusercontent.com',
    iosBundleId: 'com.example.base_code',
  );
}
